### ISSUE TITLE
Problem on Qnap

### ISSUE THREAD

**Issue by Mikypan81** [stephen/nicercast#8]
Hello, i'm trying to install airsonos on my Qnap (ARM) but I've some errore.
So, i've downloaded nicercast and i've tryied to install manually.
When i go in nicercast directory and launch
# npm install

I've this error:

npm WARN deprecated static-favicon@1.0.2: use serve-favicon module
-
> lame@1.2.1 install /opt/node/lib/node_modules/nicercast/node_modules/lame
> node-gyp rebuild

gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at failNoPython (/share/HDA_DATA/.qpkg/nodejs/node/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:103:14)
gyp ERR! stack     at /share/HDA_DATA/.qpkg/nodejs/node/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:42:11
gyp ERR! stack     at F (/share/HDA_DATA/.qpkg/nodejs/node/lib/node_modules/npm/node_modules/which/which.js:43:25)
gyp ERR! stack     at E (/share/HDA_DATA/.qpkg/nodejs/node/lib/node_modules/npm/node_modules/which/which.js:46:29)
gyp ERR! stack     at /share/HDA_DATA/.qpkg/nodejs/node/lib/node_modules/npm/node_modules/which/which.js:57:16
gyp ERR! stack     at Object.oncomplete (evalmachine.<anonymous>:108:15)
gyp ERR! System Linux 3.4.6
gyp ERR! command "node" "/share/HDA_DATA/.qpkg/nodejs/node/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /share/HDA_DATA/.qpkg/nodejs/node/lib/node_modules/nicercast/node_modules/lame
gyp ERR! node -v v0.10.35
gyp ERR! node-gyp -v v1.0.1
gyp ERR! not ok

npm ERR! lame@1.2.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the lame@1.2.1 install script.
npm ERR! This is most likely a problem with the lame package,
npm ERR! not with npm itself.

npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls lame
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 3.4.6
npm ERR! command "/opt/node/bin/node" "/opt/node/bin/npm" "install" "-g"
npm ERR! cwd /share/HDA_DATA/.qpkg/nicercast-master
npm ERR! node -v v0.10.35
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR! not ok code 0

Can anyone help me???
Who know this kind of error????

**Comment by stephen** [comment]
Building airsonos on that platform requires a python interpeter and c compiler
